packageExtensions:
  '@storybook/preset-typescript@*':
    dependencies:
      '@babel/core': '^7.9.6'
  '@vue/cli-service@*':
    peerDependencies:
      '@vue/cli-plugin-eslint': '*'
      '@vue/cli-plugin-typescript': '*'
  'fork-ts-checker-webpack-plugin@*':
    dependencies:
      'vue-template-compiler': '*'
  'jss-plugin-rule-value-function@*':
    dependencies:
      'tiny-warning': '*'
  'react-vega@*':
    dependencies:
      'prop-types': '*'
  'vega-embed@*':
    dependencies:
      'vega-util': '*'
      'tslib': '*'
  'vega-tooltip@*':
    dependencies:
      'vega-typings': '*'
  'vega-lite@*':
    dependencies:
      'vega-typings': '*'
  'prism-react-renderer@*':
    dependencies:
      react: '*'
  'react-live@*':
    dependencies:
      react: '*'
      '@philpl/buble': '*'
  'react-simple-code-editor@*':
    dependencies:
      react: '*'
  '@upsetjs/react@*':
    peerDependencies:
      'react-refresh': '*'
  'typedoc@*':
    dependencies:
      'shiki-themes': '*'
